

const wordsList= [
    { word: "mountain", hint: "A large natural elevation of the earth's surface." },
    { word: "ocean", hint: "A vast body of salt water that covers almost three-quarters of the earth's surface." },
    { word: "forest", hint: "A large area covered chiefly with trees and undergrowth." },
    { word: "desert", hint: "A barren area of landscape where little precipitation occurs." },
    { word: "river", hint: "A large natural stream of water flowing in a channel to the sea, a lake, or another river." },
    { word: "valley", hint: "A low area of land between hills or mountains, typically with a river or stream flowing through it." },
    { word: "volcano", hint: "A rupture in the crust of a planetary-mass object that allows hot lava, volcanic ash, and gases to escape from a magma chamber below the surface." },
    { word: "island", hint: "A piece of land surrounded by water." },
    { word: "waterfall", hint: "A place where water flows over a vertical drop or a series of steep drops in the course of a stream or river." },
    { word: "canyon", hint: "A deep gorge, typically one with a river flowing through it." },
    { word: "rainbow", hint: "A meteorological phenomenon caused by reflection, refraction, and dispersion of light in water droplets." },
    { word: "gorge", hint: "A narrow valley between hills or mountains, typically with steep rocky walls and a stream running through it." },
    { word: "horizon", hint: "The line at which the earth's surface and the sky appear to meet." },
    { word: "peninsula", hint: "A piece of land almost surrounded by water or projecting out into a body of water." },
    { word: "hades", hint: "The Greek god of the underworld and the dead." },
    { word: "apollo", hint: "The Greek god of music, arts, knowledge, healing, plague, prophecy, poetry, manly beauty, and archery." },
    { word: "athena", hint: "The Greek goddess of wisdom, craft, and war." },
    { word: "aphrodite", hint: "The Greek goddess of love, beauty, and desire." },
    { word: "vibhandaka", hint: "A sage and the father of Rishyasringa." },
    { word: "mandodari", hint: "The wife of Ravana, known for her wisdom and virtue." },
    { word: "subahu", hint: "A demon who, along with Mareecha, was defeated by Rama." },
    { word: "tataki", hint: "A demoness slain by Rama during his journey with Vishwamitra." },
    { word: "chitrakoot", hint: "The forest where Rama, Sita, and Lakshmana spent part of their exile." },
    { word: "dandaka", hint: "A forest where Rama, Sita, and Lakshmana spent part of their exile." },
    { word: "panchavati", hint: "The place in the forest where Sita was abducted by Ravana." },
    { word: "lakshagriha", hint: "The house of lac, a trap set by Duryodhana to kill the Pandavas." },
    { word: "uttara", hint: "The son of King Virata who fought alongside the Pandavas." },
    { word: "virata", hint: "The king in whose court the Pandavas spent their incognito exile." },
    { word: "abhimanyu", hint: "The son of Arjuna, known for his valiant efforts in the Kurukshetra war." },
    { word: "jayadratha", hint: "The king of Sindhu who caused the death of Abhimanyu." },
    { word: "satyaki", hint: "A Yadava warrior who fought for the Pandavas in the Mahabharata." },
    { word: "hermes", hint: "The Greek god of trade, thieves, travelers, sports, athletes, and border crossings, guide to the Underworld." },
    { word: "jupiter", hint: "The king of the gods in Roman mythology, equivalent to Greek Zeus." },
    { word: "venus", hint: "The Roman goddess of love, beauty, and fertility, equivalent to Greek Aphrodite." },
    { word: "prairie", hint: "A large open area of grassland." },
    { word: "savanna", hint: "A grassy plain in tropical and subtropical regions." },
    { word: "whirlpool", hint: "A powerful circular current of water." },
    { word: "pharaoh", hint: "A ruler in ancient Egypt." },
    { word: "pyramid", hint: "A monumental structure with a square or triangular base and sloping sides that meet in a point at the top." },
    { word: "renaissance", hint: "A period of European history marking the transition from the Middle Ages to modernity." },
    { word: "crusade", hint: "A series of medieval military expeditions made by Europeans to recover the Holy Land from the Muslims." },
    { word: "gladiator", hint: "A man trained to fight with weapons against other men or wild animals in an arena in ancient Rome." },
    { word: "empire", hint: "An extensive group of states or countries under a single supreme authority." },
    { word: "revolution", hint: "A forcible overthrow of a government or social order in favor of a new system." },
    { word: "colony", hint: "A country or area under the full or partial political control of another country and occupied by settlers from that country." },
    { word: "dynasty", hint: "A line of hereditary rulers of a country." },
    { word: "medieval", hint: "Relating to the Middle Ages." },
    { word: "feudalism", hint: "The dominant social system in medieval Europe." },
    { word: "imperialism", hint: "A policy of extending a country's power and influence through diplomacy or military force." },
    { word: "renaissance", hint: "The revival of art and literature under the influence of classical models in the 14th–16th centuries." },
    { word: "viking", hint: "Seafaring Scandinavian warriors who raided and colonized wide areas of Europe from the 9th to the 11th century." },
    { word: "plague", hint: "A contagious bacterial disease characterized by fever and delirium." },
    { word: "knight", hint: "A man who served his sovereign or lord as a mounted soldier in armor." },
    { word: "crusader", hint: "A participant in one of the Crusades." },
    { word: "monarchy", hint: "A form of government with a monarch at the head." },
    { word: "republic", hint: "A state in which supreme power is held by the people and their elected representatives." },
    { word: "dictator", hint: "A ruler with total power over a country, typically one who has obtained power by force." },
    { word: "constitution", hint: "A body of fundamental principles or established precedents according to which a state or other organization is governed." },
    { word: "civilization", hint: "The stage of human social and cultural development and organization that is considered most advanced." },
    { word: "industrialization", hint: "The development of industries in a country or region on a wide scale." },
    { word: "colonization", hint: "The action or process of settling among and establishing control over the indigenous people of an area." },
    { word: "armistice", hint: "An agreement made by opposing sides in a war to stop fighting for a certain time." },
    { word: "treaty", hint: "A formally concluded and ratified agreement between countries." },
    { word: "propaganda", hint: "Information, especially of a biased or misleading nature, used to promote a political cause or point of view." },
    { word: "reformation", hint: "A 16th-century movement for the reform of abuses in the Roman Catholic Church ending in the establishment of the Reformed and Protestant Churches." },
    { word: "enlightenment", hint: "An intellectual and philosophical movement that dominated the world of ideas in Europe during the 17th and 18th centuries." },
    { word: "renaissance", hint: "The period in Europe between the 14th and 17th centuries when there was a surge of interest in and production of art and literature." },
    { word: "holocaust", hint: "The mass murder of Jews under the German Nazi regime during the period 1941–45." },
    { word: "wicket", hint: "A set of stumps and bails; also refers to the dismissal of a batsman." },
    { word: "bowler", hint: "A player who delivers the ball to the batsman." },
    { word: "batsman", hint: "A player who tries to score runs by hitting the ball with a bat." },
    { word: "umpire", hint: "An official who watches the game to enforce the rules." },
    { word: "boundary", hint: "The edge of the playing field; also refers to a shot that reaches the edge of the field, scoring four or six runs." },
    { word: "run", hint: "The basic unit of scoring in cricket." },
    { word: "over", hint: "A set of six deliveries bowled by a bowler." },
    { word: "catch", hint: "A method of dismissing a batsman by catching the ball after it is hit and before it touches the ground." },
    { word: "stumps", hint: "Three vertical posts that support two bails and form the wicket." },
    { word: "bails", hint: "Two small sticks placed on top of the stumps." },
    { word: "pitch", hint: "The strip of ground between the two sets of stumps." },
    { word: "crease", hint: "A set of lines painted or etched on the pitch to help determine various points in the game." },
    { word: "duck", hint: "A score of zero by a batsman." },
    { word: "century", hint: "A score of 100 or more runs by a batsman in a single innings." },
    { word: "maiden", hint: "An over in which no runs are scored." },
    { word: "noball", hint: "An illegal delivery by the bowler, usually due to overstepping the crease." },
    { word: "wide", hint: "A delivery that is out of the batsman's reach and is not considered a fair ball." },
    { word: "yorker", hint: "A delivery bowled at the batsman's feet, typically aimed at the base of the stumps." },
    { word: "googly", hint: "A deceptive delivery bowled by a leg-spinner that turns in the opposite direction to the expected leg-spin." },
    { word: "allrounder", hint: "A player who is skilled at both batting and bowling." },
    { word: "innings", hint: "A period in which a team or a player bats until ten players are dismissed or a set number of overs have been bowled." },
    { word: "helmet", hint: "Protective gear worn by a batsman or close fielder to guard the head." },
    { word: "slip", hint: "A fielding position close to the wicket-keeper, designed to catch balls edged by the batsman." },
    { word: "swing", hint: "The movement of the ball in the air, typically caused by the bowler." },
    { word: "spin", hint: "The rotation of the ball, causing it to change direction after bouncing." },
    { word: "bouncer", hint: "A fast, short-pitched delivery that bounces high, often aimed at the batsman's head or chest." },
    { word: "cover", hint: "A fielding position on the off-side, in front of the batsman." },
    { word: "gully", hint: "A fielding position behind the slips, designed to catch edges from the batsman." },
    { word: "legspinner", hint: "A bowler who delivers balls that spin from leg to off side for a right-handed batsman." },
    { word: "offspinner", hint: "A bowler who delivers balls that spin from off to leg side for a right-handed batsman." },
    { word: "soccer", hint: "A team sport played with a spherical ball between two teams of eleven players." },
    { word: "basketball", hint: "A team sport where two teams, most commonly of five players each, oppose each other on a rectangular court." },
    { word: "tennis", hint: "A racket sport that can be played individually against a single opponent or between two teams of two players each." },
    { word: "baseball", hint: "A bat-and-ball game played between two opposing teams who take turns batting and fielding." },
    { word: "hockey", hint: "A sport in which two teams play against each other by trying to maneuver a ball or a puck into the opponent's goal using a hockey stick." },
    { word: "golf", hint: "A club-and-ball sport in which players use various clubs to hit balls into a series of holes on a course in as few strokes as possible." },
    { word: "rugby", hint: "A team sport played with an oval ball that can be kicked, carried, and passed from hand to hand." },
    { word: "cricket", hint: "A bat-and-ball game played between two teams of eleven players on a field." },
    { word: "geyser", hint: "A hot spring in which water intermittently boils, sending a tall column of water and steam into the air." },
    { word: "glacier", hint: "A slowly moving mass or river of ice formed by the accumulation and compaction of snow on mountains or near the poles." },
    { word: "savanna", hint: "A grassy plain in tropical and subtropical regions, with few trees." },
    { word: "rainforest", hint: "A dense, warm, wet forest that receives high amounts of rainfall year-round." },
    { word: "prairie", hint: "A large open area of grassland, especially in the Mississippi River valley." },
    { word: "tundra", hint: "A type of biome where the tree growth is hindered by low temperatures and short growing seasons." },
    { word: "plateau", hint: "An area of relatively level high ground." },
    { word: "reef", hint: "A ridge of jagged rock, coral, or sand just above or below the surface of the sea." },
    { word: "lake", hint: "A large body of water surrounded by land." },
    { word: "cave", hint: "A natural underground chamber in a hillside or cliff." },
    { word: "meadow", hint: "A field habitat vegetated by grass and other non-woody plants." },
    { word: "cliff", hint: "A steep face of rock and earth." },
    { word: "swamp", hint: "A wetland that is forested." },
    { word: "marsh", hint: "A wetland dominated by herbaceous rather than woody plant species." },
    { word: "fjord", hint: "A long, narrow, deep inlet of the sea between high cliffs." },
    { word: "gulf", hint: "A large deep bay with a narrow mouth." },
    { word: "lagoon", hint: "A shallow body of water separated from a larger body of water by barrier islands or reefs." },
    { word: "butte", hint: "An isolated hill with steep, often vertical sides and a small, flat top." },
    { word: "mesa", hint: "An isolated flat-topped hill with steep sides." },
    { word: "dune", hint: "A mound or ridge of sand formed by the wind." },
    { word: "cataract", hint: "A large waterfall." },
    { word: "delta", hint: "A landform at the mouth of a river created by sediment deposits." },
    { word: "estuary", hint: "The tidal mouth of a large river, where the tide meets the stream." },
    { word: "grove", hint: "A small wood or other group of trees." },
    { word: "moor", hint: "An area of open uncultivated upland." },
    { word: "oasis", hint: "A fertile spot in a desert where water is found." },
    { word: "peak", hint: "The pointed top of a mountain." },
    { word: "savannah", hint: "A grassy plain in tropical and subtropical regions, with few trees." },
    { word: "steppe", hint: "A large area of flat unforested grassland." },
    { word: "badlands", hint: "A type of dry terrain where softer sedimentary rocks and clay-rich soils have been extensively eroded." },
    { word: "fen", hint: "A type of wetland with alkaline water." },
    { word: "karst", hint: "A terrain with distinctive landforms and drainage patterns due to the dissolution of soluble rocks." },
    { word: "quagmire", hint: "A soft boggy area of land." },
    { word: "taiga", hint: "A forest of the cold, subarctic region." },
    { word: "swimming", hint: "An individual or team sport that requires the use of one's entire body to move through water." },
    { word: "cycling", hint: "The use of bicycles for transport, recreation, exercise, or sport." },
    { word: "boxing", hint: "A combat sport in which two people throw punches at each other for a predetermined amount of time in a boxing ring." },
    { word: "wrestling", hint: "A sport in which two competitors try to throw or force each other to the ground." },
    { word: "athletics", hint: "A collection of sporting events that involve competitive running, jumping, throwing, and walking." },
    { word: "skiing", hint: "A means of transport using skis to glide on snow." },
    { word: "gymnastics", hint: "A sport involving performance of exercises requiring strength, flexibility, balance, and control." },
    { word: "fencing", hint: "A sport involving fighting with swords, especially foils, epees, or sabres." },
    { word: "archery", hint: "The sport or skill of shooting with a bow and arrows, especially at a target." },
    { word: "badminton", hint: "A racquet sport played using racquets to hit a shuttlecock across a net." },
    { word: "volleyball", hint: "A team sport in which two teams of six players are separated by a net." },
    { word: "rowing", hint: "The act of propelling a boat using oars." },
    { word: "triathlon", hint: "A multisport race with three continuous and sequential endurance races." },
    { word: "surfing", hint: "The sport of riding a wave towards the shore while standing or lying on a surfboard." },
    { word: "karate", hint: "A martial art developed in the Ryukyu Kingdom that focuses on striking, kicking, knee strikes, and elbow strikes." },
    { word: "snowboarding", hint: "A recreational activity and Olympic and Paralympic sport that involves descending a snow-covered slope on a snowboard." },
    { word: "handball", hint: "A team sport in which two teams of seven players each pass a ball using their hands with the aim of throwing it into the goal of the other team." },
    { word: "lacrosse", hint: "A team sport played with a lacrosse stick and a lacrosse ball." },
    { word: "polo", hint: "A horseback team sport, where the objective is to score goals against an opposing team." },
    { word: "skateboarding", hint: "An action sport which involves riding and performing tricks using a skateboard." },
    { word: "tabletennis", hint: "A sport in which two or four players hit a lightweight ball back and forth across a table using small solid rackets." },
    { word: "equestrian", hint: "Relating to horse riding." },
    { word: "darts", hint: "A sport in which small, pointed missiles are thrown at a circular target fixed to a wall." },
    { word: "vishwamitra", hint: "A sage who played a pivotal role in the Ramayana, guiding Rama and Lakshmana." },
    { word: "bharadwaja", hint: "An ancient sage who was a disciple of Valmiki." },
    { word: "ahalya", hint: "A sage's wife who was turned to stone and later freed by Rama." },
    { word: "indrajit", hint: "The son of Ravana, known for his magical warfare and battle prowess." },
    { word: "mareecha", hint: "A demon who transformed into a golden deer to assist Ravana in abducting Sita." },
    { word: "lanka", hint: "The kingdom ruled by Ravana, located on an island." },
    { word: "kiskindha", hint: "The monkey kingdom where Rama met Hanuman and Sugriva." },
    { word: "angada", hint: "The son of Vali and a warrior in Sugriva's army." },
    { word: "manthara", hint: "The maid who instigated Queen Kaikeyi to send Rama into exile." },
    { word: "agnipariksha", hint: "The trial by fire that Sita underwent to prove her purity." },
    { word: "vidura", hint: "The wise minister and half-brother to Dhritarashtra and Pandu." },
    { word: "shikhandi", hint: "A warrior in the Mahabharata who was instrumental in Bhishma's downfall." },
    { word: "ulupi", hint: "The Naga princess who married Arjuna." },
    { word: "hidimba", hint: "A demoness who married Bhima and bore him a son, Ghatotkacha." },
    { word: "zeus", hint: "The king of the gods in Greek mythology, god of the sky and thunder." },
    { word: "hera", hint: "The queen of the gods in Greek mythology, goddess of marriage and birth." },
    { word: "poseidon", hint: "The Greek god of the sea, earthquakes, and horses." }
];


function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// Shuffle the wordsList array
const shuffledWordsList = shuffleArray(wordsList);
wordsList=shuffledWordsList;